image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_VERSION: latest
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:${IMAGE_VERSION} 
  BUILD_BRANCH: "main"

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == $BUILD_BRANCH
      changes:
        - scripts/**
        - hook/**
        - bin/amd64/zerossl-ip-cert
        - Dockerfile
      when: always

    - if: $CI_COMMIT_BRANCH == $BUILD_BRANCH
      changes:
        - scripts/**
        - Dockerfile
      when: always