image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_VERSION: v1.0.1
  DOCKER_IMAGE_NAME_LATEST: $CI_REGISTRY_IMAGE:latest
  DOCKER_IMAGE_NAME_VERSION: $CI_REGISTRY_IMAGE:${IMAGE_VERSION}
  BUILD_BRANCH: "main"

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build --build-arg VERSION=${IMAGE_VERSION} -t $DOCKER_IMAGE_NAME_LATEST -t $DOCKER_IMAGE_NAME_VERSION .
    - docker push $DOCKER_IMAGE_NAME_LATEST
    - docker push $DOCKER_IMAGE_NAME_VERSION
  rules:
    - if: $CI_COMMIT_BRANCH == $BUILD_BRANCH
      changes:
        - scripts/**
        - hook/**
        - Dockerfile
      when: always
