name: Build Docker Image for Multiple Architectures

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_VERSION: v1.0.1
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
      CI_REGISTRY_IMAGE: ghcr.io/your-labs/ip-cert
      DOCKER_IMAGE_NAME_LATEST: ghcr.io/your-labs/ip-cert:latest
      DOCKER_IMAGE_NAME_VERSION: ghcr.io/your-labs/ip-cert:v1.0.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image for Multiple Architectures
        run: |
          docker buildx create --use
          docker buildx build \
            --build-arg VERSION=${IMAGE_VERSION} \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t ${DOCKER_IMAGE_NAME_LATEST} \
            -t ${DOCKER_IMAGE_NAME_VERSION} \
            --push .
