name: Build Docker Image for Multiple Architectures

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image for Multiple Architectures
        run: |
          docker buildx create --use
          docker buildx build \
            --build-arg VERSION=v1.0.1 \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t ${{ secrets.CI_REGISTRY_IMAGE }}:latest \
            -t ${{ secrets.CI_REGISTRY_IMAGE }}:v1.0.1 \
            --push .
