name: Build Docker Image for Multiple Architectures

on:
  workflow_dispatch:

env:
  IMAGE_VERSION: v1.0.1
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  # 将 CI_REGISTRY_IMAGE 设置为 GitHub Container Registry 地址
  CI_REGISTRY_IMAGE: ghcr.io/your-labs/ip-cert
  DOCKER_IMAGE_NAME_LATEST: ${{ env.CI_REGISTRY_IMAGE }}:latest
  DOCKER_IMAGE_NAME_VERSION: ${{ env.CI_REGISTRY_IMAGE }}:${{ env.IMAGE_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image for Multiple Architectures
        run: |
          docker buildx create --use
          docker buildx build \
            --build-arg VERSION=${{ env.IMAGE_VERSION }} \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t ${{ env.DOCKER_IMAGE_NAME_LATEST }} \
            -t ${{ env.DOCKER_IMAGE_NAME_VERSION }} \
            --push .
